// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurkeyDB.Data;

#nullable disable

namespace TurkeyDB.Migrations
{
    [DbContext(typeof(TurkeyDBContext))]
    partial class TurkeyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyAPI.Model.Mountain", b =>
                {
                    b.Property<int>("MountainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MountainID"));

                    b.Property<string>("MountainName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("MountainID");

                    b.ToTable("Mountains");

                    b.HasData(
                        new
                        {
                            MountainID = 1,
                            MountainName = "Abi Gamin"
                        },
                        new
                        {
                            MountainID = 2,
                            MountainName = "Annapurna Dakshin (Annapurna South)"
                        },
                        new
                        {
                            MountainID = 3,
                            MountainName = "Annapurna I"
                        },
                        new
                        {
                            MountainID = 4,
                            MountainName = "Annapurna II"
                        },
                        new
                        {
                            MountainID = 5,
                            MountainName = "Annapurna III"
                        },
                        new
                        {
                            MountainID = 6,
                            MountainName = "Annapurna IV"
                        },
                        new
                        {
                            MountainID = 7,
                            MountainName = "Apsarasas Kangri"
                        },
                        new
                        {
                            MountainID = 8,
                            MountainName = "Baintha Brakk"
                        },
                        new
                        {
                            MountainID = 9,
                            MountainName = "The Ogre"
                        },
                        new
                        {
                            MountainID = 10,
                            MountainName = "Baltoro Kangri"
                        },
                        new
                        {
                            MountainID = 11,
                            MountainName = "Batura Sar"
                        },
                        new
                        {
                            MountainID = 12,
                            MountainName = "Broad Peak"
                        },
                        new
                        {
                            MountainID = 13,
                            MountainName = "Chamlang"
                        },
                        new
                        {
                            MountainID = 14,
                            MountainName = "Changtse"
                        },
                        new
                        {
                            MountainID = 15,
                            MountainName = "Cho Oyu"
                        },
                        new
                        {
                            MountainID = 16,
                            MountainName = "Chogolisa"
                        },
                        new
                        {
                            MountainID = 17,
                            MountainName = "Chomo Lonzo"
                        },
                        new
                        {
                            MountainID = 18,
                            MountainName = "Chongtar"
                        },
                        new
                        {
                            MountainID = 19,
                            MountainName = "Churen Himal"
                        },
                        new
                        {
                            MountainID = 20,
                            MountainName = "The Crown"
                        },
                        new
                        {
                            MountainID = 21,
                            MountainName = "Huang Guan Shan"
                        },
                        new
                        {
                            MountainID = 22,
                            MountainName = "Dhaulagiri I"
                        },
                        new
                        {
                            MountainID = 23,
                            MountainName = "Dhaulagiri II"
                        },
                        new
                        {
                            MountainID = 24,
                            MountainName = "Dhaulagiri IV"
                        },
                        new
                        {
                            MountainID = 25,
                            MountainName = "Dhaulagiri V"
                        },
                        new
                        {
                            MountainID = 26,
                            MountainName = "Dhaulagiri VI"
                        },
                        new
                        {
                            MountainID = 27,
                            MountainName = "Diran"
                        },
                        new
                        {
                            MountainID = 28,
                            MountainName = "Distaghil Sar"
                        },
                        new
                        {
                            MountainID = 29,
                            MountainName = "Mount Everest"
                        },
                        new
                        {
                            MountainID = 30,
                            MountainName = "Sagarmatha"
                        },
                        new
                        {
                            MountainID = 31,
                            MountainName = "Chomolungma"
                        },
                        new
                        {
                            MountainID = 32,
                            MountainName = "Gangapurna"
                        },
                        new
                        {
                            MountainID = 33,
                            MountainName = "Gangkhar Puensum"
                        },
                        new
                        {
                            MountainID = 34,
                            MountainName = "Gasherbrum I"
                        },
                        new
                        {
                            MountainID = 35,
                            MountainName = "Hidden Peak"
                        },
                        new
                        {
                            MountainID = 36,
                            MountainName = "Gasherbrum II"
                        },
                        new
                        {
                            MountainID = 37,
                            MountainName = "Gasherbrum III"
                        },
                        new
                        {
                            MountainID = 38,
                            MountainName = "Gasherbrum IV"
                        },
                        new
                        {
                            MountainID = 39,
                            MountainName = "Ghent Kangri"
                        },
                        new
                        {
                            MountainID = 40,
                            MountainName = "Gimmigela Chuli"
                        },
                        new
                        {
                            MountainID = 41,
                            MountainName = "The Twins"
                        },
                        new
                        {
                            MountainID = 42,
                            MountainName = "Gongga Shan"
                        },
                        new
                        {
                            MountainID = 43,
                            MountainName = "Minya Konka"
                        },
                        new
                        {
                            MountainID = 44,
                            MountainName = "Gurla Mandhata"
                        },
                        new
                        {
                            MountainID = 45,
                            MountainName = "Gyachung Kang"
                        },
                        new
                        {
                            MountainID = 46,
                            MountainName = "Gyala Peri"
                        },
                        new
                        {
                            MountainID = 47,
                            MountainName = "Haramosh Peak"
                        },
                        new
                        {
                            MountainID = 48,
                            MountainName = "Himalchuli"
                        },
                        new
                        {
                            MountainID = 49,
                            MountainName = "Ismoil Somoni Peak"
                        },
                        new
                        {
                            MountainID = 50,
                            MountainName = "Istor-o-Nal"
                        },
                        new
                        {
                            MountainID = 51,
                            MountainName = "Kumbhakarna"
                        },
                        new
                        {
                            MountainID = 52,
                            MountainName = "Jannu"
                        },
                        new
                        {
                            MountainID = 53,
                            MountainName = "Jengish Chokusu"
                        },
                        new
                        {
                            MountainID = 54,
                            MountainName = "Tömür"
                        },
                        new
                        {
                            MountainID = 55,
                            MountainName = "Pik Pobedy"
                        },
                        new
                        {
                            MountainID = 56,
                            MountainName = "Jomolhari"
                        },
                        new
                        {
                            MountainID = 57,
                            MountainName = "Chomo Lhari"
                        },
                        new
                        {
                            MountainID = 58,
                            MountainName = "Jongsong Peak"
                        },
                        new
                        {
                            MountainID = 59,
                            MountainName = "Baltistan Peak"
                        },
                        new
                        {
                            MountainID = 60,
                            MountainName = "Kabru N"
                        },
                        new
                        {
                            MountainID = 61,
                            MountainName = "Kamet"
                        },
                        new
                        {
                            MountainID = 62,
                            MountainName = "Kangchenjunga"
                        },
                        new
                        {
                            MountainID = 63,
                            MountainName = "Kangpenqing"
                        },
                        new
                        {
                            MountainID = 64,
                            MountainName = "Gang Benchhen"
                        },
                        new
                        {
                            MountainID = 65,
                            MountainName = "Kangphu Kang"
                        },
                        new
                        {
                            MountainID = 66,
                            MountainName = "Shimokangri"
                        },
                        new
                        {
                            MountainID = 67,
                            MountainName = "Kanjut Sar"
                        },
                        new
                        {
                            MountainID = 68,
                            MountainName = "Karjiang"
                        },
                        new
                        {
                            MountainID = 69,
                            MountainName = "Khartaphu"
                        },
                        new
                        {
                            MountainID = 70,
                            MountainName = "Khunyang Chhish"
                        },
                        new
                        {
                            MountainID = 71,
                            MountainName = "Kirat Chuli"
                        },
                        new
                        {
                            MountainID = 72,
                            MountainName = "Kongur Tagh"
                        },
                        new
                        {
                            MountainID = 73,
                            MountainName = "Kongur Tiube"
                        },
                        new
                        {
                            MountainID = 74,
                            MountainName = "Kula Kangri"
                        },
                        new
                        {
                            MountainID = 75,
                            MountainName = "Labuche Kang"
                        },
                        new
                        {
                            MountainID = 76,
                            MountainName = "Labuche Kang III"
                        },
                        new
                        {
                            MountainID = 77,
                            MountainName = "Labuche Kang East"
                        },
                        new
                        {
                            MountainID = 78,
                            MountainName = "Langtang Lirung"
                        },
                        new
                        {
                            MountainID = 79,
                            MountainName = "Langtang Ri"
                        },
                        new
                        {
                            MountainID = 80,
                            MountainName = "Lhotse"
                        },
                        new
                        {
                            MountainID = 81,
                            MountainName = "Lupghar Sar"
                        },
                        new
                        {
                            MountainID = 82,
                            MountainName = "Makalu"
                        },
                        new
                        {
                            MountainID = 83,
                            MountainName = "Malangutti Sar"
                        },
                        new
                        {
                            MountainID = 84,
                            MountainName = "Malubiting"
                        },
                        new
                        {
                            MountainID = 85,
                            MountainName = "Mamostong Kangri"
                        },
                        new
                        {
                            MountainID = 86,
                            MountainName = "Mana Peak"
                        },
                        new
                        {
                            MountainID = 87,
                            MountainName = "Manaslu"
                        },
                        new
                        {
                            MountainID = 88,
                            MountainName = "Masherbrum"
                        },
                        new
                        {
                            MountainID = 89,
                            MountainName = "Molamenqing"
                        },
                        new
                        {
                            MountainID = 90,
                            MountainName = "Momhil Sar"
                        },
                        new
                        {
                            MountainID = 91,
                            MountainName = "Mukut Parbat"
                        },
                        new
                        {
                            MountainID = 92,
                            MountainName = "Muztagh Ata"
                        },
                        new
                        {
                            MountainID = 93,
                            MountainName = "Muztagh Tower"
                        },
                        new
                        {
                            MountainID = 94,
                            MountainName = "Namcha Barwa"
                        },
                        new
                        {
                            MountainID = 95,
                            MountainName = "Nanda Devi"
                        },
                        new
                        {
                            MountainID = 96,
                            MountainName = "Nanga Parbat"
                        },
                        new
                        {
                            MountainID = 97,
                            MountainName = "Nangpai Gosum"
                        },
                        new
                        {
                            MountainID = 98,
                            MountainName = "Ngadi Chuli"
                        },
                        new
                        {
                            MountainID = 99,
                            MountainName = "Noijin Kangsang"
                        },
                        new
                        {
                            MountainID = 100,
                            MountainName = "Norin Kang"
                        },
                        new
                        {
                            MountainID = 101,
                            MountainName = "Noshaq"
                        },
                        new
                        {
                            MountainID = 102,
                            MountainName = "Nuptse"
                        },
                        new
                        {
                            MountainID = 103,
                            MountainName = "Passu Sar"
                        },
                        new
                        {
                            MountainID = 104,
                            MountainName = "Porong Ri"
                        },
                        new
                        {
                            MountainID = 105,
                            MountainName = "Pumari Chhish"
                        },
                        new
                        {
                            MountainID = 106,
                            MountainName = "Putha Hiunchuli"
                        },
                        new
                        {
                            MountainID = 107,
                            MountainName = "Rakaposhi"
                        },
                        new
                        {
                            MountainID = 108,
                            MountainName = "Rimo I"
                        },
                        new
                        {
                            MountainID = 109,
                            MountainName = "Rimo III"
                        },
                        new
                        {
                            MountainID = 110,
                            MountainName = "Saltoro Kangri"
                        },
                        new
                        {
                            MountainID = 111,
                            MountainName = "Saraghrar"
                        },
                        new
                        {
                            MountainID = 112,
                            MountainName = "Saser Kangri I"
                        },
                        new
                        {
                            MountainID = 113,
                            MountainName = "Saser Kangri II E"
                        },
                        new
                        {
                            MountainID = 114,
                            MountainName = "Saser Kangri III"
                        },
                        new
                        {
                            MountainID = 115,
                            MountainName = "Sherpi Kangri"
                        },
                        new
                        {
                            MountainID = 116,
                            MountainName = "Shishapangma"
                        },
                        new
                        {
                            MountainID = 117,
                            MountainName = "Gosainthan"
                        },
                        new
                        {
                            MountainID = 118,
                            MountainName = "Shispare"
                        },
                        new
                        {
                            MountainID = 119,
                            MountainName = "Sia Kangri"
                        },
                        new
                        {
                            MountainID = 120,
                            MountainName = "Siguang Ri"
                        },
                        new
                        {
                            MountainID = 121,
                            MountainName = "Singhi Kangri"
                        },
                        new
                        {
                            MountainID = 122,
                            MountainName = "Skil Brum"
                        },
                        new
                        {
                            MountainID = 123,
                            MountainName = "Skyang Kangri"
                        },
                        new
                        {
                            MountainID = 124,
                            MountainName = "Sunanda Devi"
                        },
                        new
                        {
                            MountainID = 125,
                            MountainName = "Nanda Devi East"
                        },
                        new
                        {
                            MountainID = 126,
                            MountainName = "Talung"
                        },
                        new
                        {
                            MountainID = 127,
                            MountainName = "Teram Kangri I"
                        },
                        new
                        {
                            MountainID = 128,
                            MountainName = "Teram Kangri III"
                        },
                        new
                        {
                            MountainID = 129,
                            MountainName = "Tirich Mir"
                        },
                        new
                        {
                            MountainID = 130,
                            MountainName = "Tongshanjiabu"
                        },
                        new
                        {
                            MountainID = 131,
                            MountainName = "Trivor"
                        },
                        new
                        {
                            MountainID = 132,
                            MountainName = "Ultar"
                        },
                        new
                        {
                            MountainID = 133,
                            MountainName = "Yangra"
                        },
                        new
                        {
                            MountainID = 134,
                            MountainName = "Ganesh I"
                        },
                        new
                        {
                            MountainID = 135,
                            MountainName = "Yukshin Gardan Sar"
                        },
                        new
                        {
                            MountainID = 136,
                            MountainName = "Yutmaru Sar"
                        },
                        new
                        {
                            MountainID = 137,
                            MountainName = "Ağrı Dağı"
                        },
                        new
                        {
                            MountainID = 138,
                            MountainName = "Cilo Dağı"
                        },
                        new
                        {
                            MountainID = 139,
                            MountainName = "Süphan Dağı"
                        },
                        new
                        {
                            MountainID = 140,
                            MountainName = "Kaçkar Dağı"
                        },
                        new
                        {
                            MountainID = 141,
                            MountainName = "Erciyes Dağı"
                        },
                        new
                        {
                            MountainID = 142,
                            MountainName = "Küçükağrı Dağı"
                        },
                        new
                        {
                            MountainID = 143,
                            MountainName = "Kızılkaya Dağı"
                        },
                        new
                        {
                            MountainID = 144,
                            MountainName = "Demirkazık Dağı"
                        },
                        new
                        {
                            MountainID = 145,
                            MountainName = "Emler"
                        },
                        new
                        {
                            MountainID = 146,
                            MountainName = "Artos Dağı"
                        },
                        new
                        {
                            MountainID = 147,
                            MountainName = "Mercan Dağları"
                        },
                        new
                        {
                            MountainID = 148,
                            MountainName = "Tendürek Dağı"
                        },
                        new
                        {
                            MountainID = 149,
                            MountainName = "Koçbaşı Dağı"
                        },
                        new
                        {
                            MountainID = 150,
                            MountainName = "Aydos Dağı"
                        },
                        new
                        {
                            MountainID = 151,
                            MountainName = "Medetsiz Dağı"
                        },
                        new
                        {
                            MountainID = 152,
                            MountainName = "Kösedağ"
                        },
                        new
                        {
                            MountainID = 153,
                            MountainName = "Hasan Dağı"
                        },
                        new
                        {
                            MountainID = 154,
                            MountainName = "Kısır Dağı"
                        },
                        new
                        {
                            MountainID = 155,
                            MountainName = "Erek Dağı"
                        },
                        new
                        {
                            MountainID = 156,
                            MountainName = "Palandöken Dağı"
                        },
                        new
                        {
                            MountainID = 157,
                            MountainName = "Ulubaba Dağı"
                        },
                        new
                        {
                            MountainID = 158,
                            MountainName = "Berit Dağı"
                        },
                        new
                        {
                            MountainID = 159,
                            MountainName = "Nurhak Dağı"
                        },
                        new
                        {
                            MountainID = 160,
                            MountainName = "Uludağ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
